# Databricks notebook source
# MAGIC %md
# MAGIC ## Auto-generated ingestion notebook
# MAGIC **Source:** csv — `sample_data/sample.csv`
# MAGIC **Target:** `main.bronze.customers`
# MAGIC **Generated by:** ingestion codegen prototype — schema captured at generation time, not re-inferred on every run.

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField,
    BooleanType,
    DoubleType,
    LongType,
    StringType
)
import uuid

# COMMAND ----------

# Parameters — these become Databricks Job parameters once deployment
# automation (Phase 3) wires this notebook to the Jobs API.
dbutils.widgets.text("source_path", "sample_data/sample.csv")
dbutils.widgets.text("batch_id", str(uuid.uuid4()))

source_path = dbutils.widgets.get("source_path")
batch_id = dbutils.widgets.get("batch_id")

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("customer_id", LongType(), False),

    StructField("first_name", StringType(), False),

    StructField("last_name", StringType(), False),

    StructField("email", StringType(), False),

    StructField("signup_date", StringType(), False),

    StructField("lifetime_value", DoubleType(), False),

    StructField("is_active", BooleanType(), False),

])

# COMMAND ----------

df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)

# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.input_file_name())
    .withColumn("_batch_id", F.lit(batch_id))
)

# COMMAND ----------

target_table = "main.bronze.customers"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (
    customer_id BIGINT,
    first_name STRING,
    last_name STRING,
    email STRING,
    signup_date STRING,
    lifetime_value DOUBLE,
    is_active BOOLEAN,
    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

# COMMAND ----------

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")