# Databricks notebook source
# MAGIC %md
# MAGIC ## Auto-generated ingestion notebook (COBOL / mainframe)
# MAGIC **Source:** COBOL copybook `/Volumes/viz_ilab/codegen_bronze/testdata/CUSTOMER.CPY.txt` — data file `/Volumes/viz_ilab/codegen_bronze/testdata/CUSTOMER.DAT.txt`
# MAGIC **Target:** `viz_ilab.codegen_bronze.cust_cobol_3`
# MAGIC **Generated by:** ingestion codegen prototype.
# MAGIC
# MAGIC Unlike the other generated notebooks in this project, this one does
# MAGIC **not** bake in a fixed schema — Cobrix re-derives the schema from
# MAGIC the copybook on every run instead. That's a deliberate exception to
# MAGIC this project's usual "fixed schema, captured once" rule: the
# MAGIC copybook is the stable, authoritative contract (versioned and
# MAGIC change-controlled by the mainframe team), not a sample file that
# MAGIC could drift between runs — so re-deriving from it is the correct
# MAGIC idiom here, not a shortcut.
# MAGIC
# MAGIC Requires the Cobrix library attached to the cluster this runs on,
# MAGIC with the Scala suffix matching this cluster's Spark version:
# MAGIC za.co.absa.cobrix:spark-cobol_2.12:2.11.0 for Spark 3.x / DBR <=16.x,
# MAGIC za.co.absa.cobrix:spark-cobol_2.13:2.11.0 for Spark 4.0+ / DBR 17.x+.
# MAGIC Getting this wrong fails the run with a generic internal error, not
# MAGIC a clear "wrong Scala version" message — see README for setup.

# COMMAND ----------

from pyspark.sql import functions as F
import uuid

# COMMAND ----------

# Parameters — set by the Databricks Job's base_parameters at deploy time
# (see deploy_cli.py / databricks_deploy.py), falling back to these
# defaults if run interactively without a job.
dbutils.widgets.text("copybook_path", "/Volumes/viz_ilab/codegen_bronze/testdata/CUSTOMER.CPY.txt")
dbutils.widgets.text("source_path", "/Volumes/viz_ilab/codegen_bronze/testdata/CUSTOMER.DAT.txt")
dbutils.widgets.text("batch_id", str(uuid.uuid4()))

copybook_path = dbutils.widgets.get("copybook_path")
source_path = dbutils.widgets.get("source_path")
batch_id = dbutils.widgets.get("batch_id")

# COMMAND ----------

df = (
    spark.read.format("cobol")
    .option("copybook", copybook_path)
    
    .option("is_text", "true")
    .load(source_path)
)

# COMMAND ----------

# Flattens COBOL group items (level 05 with child level-10s) into their
# leaf fields — Cobrix maps a group to a Spark StructType column, but the
# Bronze table below declares flat scalar columns, so this has to happen
# before the write or every group column fails to merge into its (flat)
# Delta column. This mapping was captured once at generation time (from
# the schema you reviewed), same "fixed once, not re-derived per run"
# reasoning as the DDL below — it only needs regenerating if the copybook
# itself changes shape.
df = df.select(
    F.col("CUST_ID").alias("CUST_ID"),
    F.col("CUST_NAME").getField("CUST_FIRST_NAME").alias("CUST_NAME_CUST_FIRST_NAME"),
    F.col("CUST_NAME").getField("CUST_MIDDLE_INIT").alias("CUST_NAME_CUST_MIDDLE_INIT"),
    F.col("CUST_NAME").getField("CUST_LAST_NAME").alias("CUST_NAME_CUST_LAST_NAME"),
    F.col("CUST_ADDRESS").getField("CUST_STREET_LINE1").alias("CUST_ADDRESS_CUST_STREET_LINE1"),
    F.col("CUST_ADDRESS").getField("CUST_STREET_LINE2").alias("CUST_ADDRESS_CUST_STREET_LINE2"),
    F.col("CUST_ADDRESS").getField("CUST_CITY").alias("CUST_ADDRESS_CUST_CITY"),
    F.col("CUST_ADDRESS").getField("CUST_STATE_CODE").alias("CUST_ADDRESS_CUST_STATE_CODE"),
    F.col("CUST_ADDRESS").getField("CUST_ZIP_CODE").alias("CUST_ADDRESS_CUST_ZIP_CODE"),
    F.col("CUST_ADDRESS").getField("CUST_COUNTRY_CODE").alias("CUST_ADDRESS_CUST_COUNTRY_CODE"),
    F.col("CUST_CONTACT").getField("CUST_PHONE").alias("CUST_CONTACT_CUST_PHONE"),
    F.col("CUST_CONTACT").getField("CUST_EMAIL").alias("CUST_CONTACT_CUST_EMAIL"),
    F.col("CUST_TYPE").alias("CUST_TYPE"),
    F.col("CUST_DATE_ADDED").alias("CUST_DATE_ADDED"),
    F.col("CUST_DATE_MODIFIED").alias("CUST_DATE_MODIFIED"),
    F.col("CUST_STATUS").alias("CUST_STATUS"),
)

# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
# Note: F.lit(source_path), not the _metadata pseudo-column — _metadata is
# only populated for Spark's native file sources (csv/json/xml/etc.);
# Cobrix is a third-party source and doesn't expose it.
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.lit(source_path))
    .withColumn("_batch_id", F.lit(batch_id))
)

# COMMAND ----------

target_table = "viz_ilab.codegen_bronze.cust_cobol_3"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (
    CUST_ID INT,
    CUST_NAME_CUST_FIRST_NAME STRING,
    CUST_NAME_CUST_MIDDLE_INIT STRING,
    CUST_NAME_CUST_LAST_NAME STRING,
    CUST_ADDRESS_CUST_STREET_LINE1 STRING,
    CUST_ADDRESS_CUST_STREET_LINE2 STRING,
    CUST_ADDRESS_CUST_CITY STRING,
    CUST_ADDRESS_CUST_STATE_CODE STRING,
    CUST_ADDRESS_CUST_ZIP_CODE STRING,
    CUST_ADDRESS_CUST_COUNTRY_CODE STRING,
    CUST_CONTACT_CUST_PHONE STRING,
    CUST_CONTACT_CUST_EMAIL STRING,
    CUST_TYPE STRING,
    CUST_DATE_ADDED INT,
    CUST_DATE_MODIFIED INT,
    CUST_STATUS STRING,
    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")