# Databricks notebook source
# MAGIC %md
# MAGIC ## Auto-generated multi-file ingestion notebook
# MAGIC **Source:** csv files under `C:\Sree\PyProject\ingestion-codegen\sample_data`
# MAGIC **Tables:** customer, order, order_item, product, sample
# MAGIC **Generated by:** ingestion codegen prototype — schema captured at generation time, not re-inferred on every run. One job ingests every table above, sequentially, in this single notebook.

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField,
    BooleanType,
    DoubleType,
    LongType,
    StringType
)
import uuid

# COMMAND ----------

# Parameters — set by the Databricks Job's base_parameters at deploy time
# (see deploy_cli.py / databricks_deploy.py), falling back to this default
# if run interactively without a job. One folder path covers every table
# below — each table's filename (captured at generation time) is joined
# onto it at run time, so redeploying against a different folder doesn't
# require regenerating the notebook.
dbutils.widgets.text("source_path", "C:\Sree\PyProject\ingestion-codegen\sample_data")
dbutils.widgets.text("batch_id", str(uuid.uuid4()))

source_folder = dbutils.widgets.get("source_path").rstrip("/")
batch_id = dbutils.widgets.get("batch_id")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Table: `customer` — from `customer.csv`

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("customer_id", LongType(), False),

    StructField("customer_name", StringType(), False),

    StructField("email", StringType(), False),

    StructField("gender", StringType(), False),

    StructField("created_ts", StringType(), False),

])

source_path = f"{source_folder}/customer.csv"

# COMMAND ----------


df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

target_table = "viz_ilab.codegen_bronze.customer"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (

    customer_id BIGINT,

    customer_name STRING,

    email STRING,

    gender STRING,

    created_ts STRING,

    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Table: `order` — from `order.csv`

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("order_id", LongType(), False),

    StructField("customer_id", LongType(), False),

    StructField("order_date", StringType(), False),

    StructField("order_status", StringType(), False),

    StructField("completed_at", StringType(), True),

])

source_path = f"{source_folder}/order.csv"

# COMMAND ----------


df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

target_table = "viz_ilab.codegen_bronze.order"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (

    order_id BIGINT,

    customer_id BIGINT,

    order_date STRING,

    order_status STRING,

    completed_at STRING,

    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Table: `order_item` — from `order_item.csv`

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("order_item_id", LongType(), False),

    StructField("order_id", LongType(), False),

    StructField("product_id", LongType(), False),

    StructField("quantity", LongType(), False),

    StructField("item_status", StringType(), False),

    StructField("delivered_at", StringType(), True),

])

source_path = f"{source_folder}/order_item.csv"

# COMMAND ----------


df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

target_table = "viz_ilab.codegen_bronze.order_item"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (

    order_item_id BIGINT,

    order_id BIGINT,

    product_id BIGINT,

    quantity BIGINT,

    item_status STRING,

    delivered_at STRING,

    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Table: `product` — from `product.csv`

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("product_id", LongType(), False),

    StructField("product_name", StringType(), False),

    StructField("category", StringType(), False),

    StructField("price", DoubleType(), False),

])

source_path = f"{source_folder}/product.csv"

# COMMAND ----------


df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

target_table = "viz_ilab.codegen_bronze.product"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (

    product_id BIGINT,

    product_name STRING,

    category STRING,

    price DOUBLE,

    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Table: `sample` — from `sample.csv`

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("customer_id", LongType(), False),

    StructField("first_name", StringType(), False),

    StructField("last_name", StringType(), False),

    StructField("email", StringType(), False),

    StructField("signup_date", StringType(), False),

    StructField("lifetime_value", DoubleType(), False),

    StructField("is_active", BooleanType(), False),

])

source_path = f"{source_folder}/sample.csv"

# COMMAND ----------


df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

target_table = "viz_ilab.codegen_bronze.sample"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (

    customer_id BIGINT,

    first_name STRING,

    last_name STRING,

    email STRING,

    signup_date STRING,

    lifetime_value DOUBLE,

    is_active BOOLEAN,

    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")

# COMMAND ----------

print("Multi-file ingestion job complete.")