# Databricks notebook source
# MAGIC %md
# MAGIC ## Auto-generated ingestion notebook
# MAGIC **Source:** csv — `C:\Users\sreek\AppData\Local\Temp\tmp4aro6jii.csv`
# MAGIC **Target:** `viz_ilab.codegen_bronze.product_test`
# MAGIC **Generated by:** ingestion codegen prototype — schema captured at generation time, not re-inferred on every run.

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField,
    DoubleType,
    LongType,
    StringType
)
import uuid

# COMMAND ----------

# Parameters — set by the Databricks Job's base_parameters at deploy time
# (see deploy_cli.py / databricks_deploy.py), falling back to this default
# if run interactively without a job.
dbutils.widgets.text("source_path", "C:\Users\sreek\AppData\Local\Temp\tmp4aro6jii.csv")
dbutils.widgets.text("batch_id", str(uuid.uuid4()))

source_path = dbutils.widgets.get("source_path")
batch_id = dbutils.widgets.get("batch_id")

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("product_id", LongType(), False),

    StructField("product_name", StringType(), False),

    StructField("category", StringType(), False),

    StructField("price", DoubleType(), False),

])

# COMMAND ----------


df = (
    spark.read
    .option("header", "true")
    .option("delimiter", ",")
    .schema(schema)
    .csv(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
# Note: F.col("_metadata.file_path") rather than the legacy F.input_file_name() —
# the older function doesn't reliably resolve paths for files read from
# Unity Catalog Volumes, which is where sources land in this design.
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

# COMMAND ----------

target_table = "viz_ilab.codegen_bronze.product_test"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (
    product_id BIGINT,
    product_name STRING,
    category STRING,
    price DOUBLE,
    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

# COMMAND ----------

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")