# Databricks notebook source
# MAGIC %md
# MAGIC ## Auto-generated ingestion notebook
# MAGIC **Source:** xml — `/Volumes/viz_ilab/codegen_bronze/testdata/sample_test.xml`
# MAGIC **Target:** `viz_ilab.codegen_bronze.xsd_test`
# MAGIC **Generated by:** ingestion codegen prototype — schema captured at generation time, not re-inferred on every run.

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField,
    BooleanType,
    DoubleType,
    LongType,
    StringType
)
import uuid

# COMMAND ----------

# Parameters — set by the Databricks Job's base_parameters at deploy time
# (see deploy_cli.py / databricks_deploy.py), falling back to this default
# if run interactively without a job.
dbutils.widgets.text("source_path", "/Volumes/viz_ilab/codegen_bronze/testdata/sample_test.xml")
dbutils.widgets.text("batch_id", str(uuid.uuid4()))

source_path = dbutils.widgets.get("source_path")
batch_id = dbutils.widgets.get("batch_id")

# COMMAND ----------

# Schema captured from the source sample at generation time.
# Deliberately NOT using inferSchema at read time — a fixed schema keeps
# every run deterministic instead of silently reinterpreting types if a
# later file looks slightly different.
schema = StructType([

    StructField("customer_id", LongType(), False),

    StructField("first_name", StringType(), False),

    StructField("last_name", StringType(), False),

    StructField("email", StringType(), False),

    StructField("signup_date", StringType(), False),

    StructField("lifetime_value", DoubleType(), False),

    StructField("is_active", BooleanType(), False),

])

# COMMAND ----------


# Requires the spark-xml data source — bundled natively in Databricks
# Runtime 14.3+; on older runtimes, attach com.databricks:spark-xml_2.12
# to the cluster first.
df = (
    spark.read
    .format("xml")
    .option("rowTag", "record")
    .schema(schema)
    .load(source_path)
)


# COMMAND ----------

# Standard lineage columns — every generated pipeline adds these, per PRD Section 5.5
# Note: F.col("_metadata.file_path") rather than the legacy F.input_file_name() —
# the older function doesn't reliably resolve paths for files read from
# Unity Catalog Volumes, which is where sources land in this design.
df = (
    df
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_batch_id", F.lit(batch_id))
)

# COMMAND ----------

target_table = "viz_ilab.codegen_bronze.xsd_test"

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {target_table} (
    customer_id BIGINT,
    first_name STRING,
    last_name STRING,
    email STRING,
    signup_date STRING,
    lifetime_value DOUBLE,
    is_active BOOLEAN,
    _ingested_at TIMESTAMP,
    _source_file STRING,
    _batch_id STRING
)
USING DELTA
""")

df.write.mode("append").saveAsTable(target_table)

# COMMAND ----------

print(f"Ingested {df.count()} rows into {target_table} (batch_id={batch_id})")